project:
  type: website
  output-dir: docs

website:
  title: "Viviana Ugalde"
  navbar:
    background: dark
    left:
      - text: "Home"
        file: index.qmd

format:
  html:
    theme: darkly
    css: styles.css